title: Ruby-Anil-utilitu
author: AnilCHoudhury-Eaton
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The tool will help you to analyze any code and get all cybersecurity issues in the code.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
